### ISSUE TITLE
M131 addeds react typing causing problems

### ISSUE THREAD

**Issue by davesmits** [microsoft/vss-web-extension-sdk#88] opened 2018-05-08 07:18 UTC
Since M131 the react types are added to the package. for my projects this causing all kind of compile exceptions. Tried to remove my react types but seems that gives lot of other problems. Can you remove this type again as it was before?

**Comment by Michaelvsk** [comment] 2018-11-26 11:00
I have the same problem and spend almost a week on trying to solve that issue but failed. Now I just read in #108 that this SDK has been superseeded by https://github.com/Microsoft/azure-devops-extension-sdk. This one comes without @types dependencies. :)
Though haven't tried the news SDK, yet.

**Comment by pabrams** [comment] 2019-04-03 15:02
How do we resolve this?  I've wasted weeks of my life trying to get this sdk working with modern versions of react and typescript. I've added a separate issue to re-open #108.  I get nauseous when I work with this sdk.

**Comment by Michaelvsk** [comment] 2019-04-03 16:04
Maybe the easiest intermediate solution is to fork this project and change the package.json to solve this issue. Maybe they even accept a solving pull request.
I would giver it a try but currently not working on a project where I need this SDK. The new SDK also shows slow progress, so this SDK probably has to be used for quite a time.

**Comment by pabrams** [comment] 2019-04-03 16:35
Unfortunately my organization won't allow me to PR, and I don't want to maintain my own version of this thing.  Maybe I'll just stop using it.

**Comment by smardine** [comment] 2019-04-04 11:27
hello, have tried to put this in your tsconfig.json?
 `"exclude": [
    "node_modules"    
  ]`
this way when you compile, the folder "node_modules" is ignored

**Comment by pabrams** [comment] 2019-04-04 13:59
Yes, I have that, thanks, but that doesn't remove the type dependencies.

**Comment by Michaelvsk** [comment] 2019-04-04 19:16
@smardine 
Also tried this approach but didn't solve the problem. :(

**Comment by Michaelvsk** [comment] 2019-04-04 19:20
@pabrams 
Maintaining your own version dosen't seem to be a big issue - the last release of this library was two years ago. It would even doubt then that a PR would be accepted, merged and a new release pushed to npm. :/

**Comment by pabrams** [comment] 2019-04-04 20:45
@Michaelvsk I guess you have a point.  First, I'm trying to figure out whether azure-devops-extension-sdk is supposed to support my TFS 2017 Update3

**Comment by pabrams** [comment] 2019-04-05 21:39
I really want to know what the problem is. Maybe I should have been a garbage man instead of a coder.  https://stackoverflow.com/questions/55543668/module-has-not-been-loaded-yet-use-require

**Closed** 2021-02-26 21:53 UTC
